// This file exports all route configurations for easy maintenance
export const routes = {
  home: '/',
  calculators: '/calculators',
  sleepCycle: '/calculators/sleep-cycle',
  bedtime: '/calculators/bedtime',
  wakeUp: '/calculators/wake-up',
  sleepDuration: '/calculators/sleep-duration',
  sleepDebt: '/calculators/sleep-debt',
  nap: '/calculators/nap',
  jetLag: '/calculators/jet-lag',
  shiftWork: '/calculators/shift-work',
  sleepDiary: '/tools/sleep-diary',
  sleepConsistency: '/tools/sleep-consistency',
  sleepSchedule: '/tools/sleep-schedule',
  education: '/education',
  educationSleepCycles: '/education/sleep-cycles',
  educationSleepHygiene: '/education/sleep-hygiene',
  educationSleepSchedule: '/education/sleep-schedule',
  educationCaffeine: '/education/caffeine-sleep',
  educationSleepMyths: '/education/sleep-myths',
  educationScreenTime: '/education/screen-time',
  educationExercise: '/education/exercise-sleep',
  educationTravel: '/education/travel-sleep',
  educationShiftWork: '/education/shift-work',
  educationChildren: '/education/children-sleep',
  educationTeen: '/education/teen-sleep',
  educationAdult: '/education/adult-sleep',
  educationNapping: '/education/napping',
  educationJetLag: '/education/jet-lag',
  faq: '/faq',
  about: '/about',
  contact: '/contact',
  privacyPolicy: '/privacy-policy',
  termsOfUse: '/terms-of-use',
  cookiePolicy: '/cookie-policy',
  disclaimer: '/disclaimer',
  editorialPolicy: '/editorial-policy',
} as const;

export type RouteKey = keyof typeof routes;
export type RoutePath = typeof routes[RouteKey];
