import { useState } from 'react';
import { Printer, Download } from 'lucide-react';

interface ScheduleDay {
  day: string;
  bedtime: string;
  wakeTime: string;
  duration: number;
  notes: string;
}

interface SleepSchedulePrintableProps {
  schedule: ScheduleDay[];
  title?: string;
}

export default function SleepSchedulePrintable({ schedule, title = 'Weekly Sleep Schedule' }: SleepSchedulePrintableProps) {
  const [showPrintable, setShowPrintable] = useState(false);

  const handlePrint = () => {
    setShowPrintable(true);
    setTimeout(() => {
      window.print();
      setShowPrintable(false);
    }, 100);
  };

  const handleDownload = () => {
    // Create a printable version
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${title}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
            h1 { color: #0ca5e9; text-align: center; }
            table { width: 100%; border-collapse: collapse; margin: 20px 0; }
            th, td { padding: 12px; border: 1px solid #ddd; text-align: left; }
            th { background-color: #f0f9ff; }
            .footer { text-align: center; margin-top: 30px; font-size: 14px; color: #666; }
          </style>
        </head>
        <body>
          <h1>${title}</h1>
          <table>
            <thead>
              <tr>
                <th>Day</th>
                <th>Bedtime</th>
                <th>Wake Time</th>
                <th>Duration</th>
                <th>Notes</th>
              </tr>
            </thead>
            <tbody>
              ${schedule.map(day => `
                <tr>
                  <td>${day.day}</td>
                  <td>${day.bedtime}</td>
                  <td>${day.wakeTime}</td>
                  <td>${day.duration} hours</td>
                  <td>${day.notes || '-'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          <div class="footer">
            <p>Generated by SleepWise - www.sleepwise.com</p>
            <p>This is a planning tool only. Individual sleep needs may vary.</p>
          </div>
        </body>
      </html>
    `;

    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => {
      printWindow.print();
    }, 500);
  };

  return (
    <div>
      <div className="flex flex-col sm:flex-row gap-3 mb-4">
        <button
          onClick={handlePrint}
          className="btn-primary flex-1"
          aria-label="Print schedule"
        >
          <Printer className="w-5 h-5 mr-2" aria-hidden="true" />
          Print Schedule
        </button>
        <button
          onClick={handleDownload}
          className="btn-secondary flex-1"
          aria-label="Download schedule"
        >
          <Download className="w-5 h-5 mr-2" aria-hidden="true" />
          Download PDF
        </button>
      </div>

      {showPrintable && (
        <div className="hidden print:block">
          <h1 className="text-2xl font-bold text-center mb-4">{title}</h1>
          <table className="w-full border-collapse">
            <thead>
              <tr className="bg-gray-100">
                <th className="border p-2 text-left">Day</th>
                <th className="border p-2 text-left">Bedtime</th>
                <th className="border p-2 text-left">Wake Time</th>
                <th className="border p-2 text-left">Duration</th>
                <th className="border p-2 text-left">Notes</th>
              </tr>
            </thead>
            <tbody>
              {schedule.map((day) => (
                <tr key={day.day}>
                  <td className="border p-2">{day.day}</td>
                  <td className="border p-2">{day.bedtime}</td>
                  <td className="border p-2">{day.wakeTime}</td>
                  <td className="border p-2">{day.duration} hours</td>
                  <td className="border p-2">{day.notes || '-'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
